# Generated by Django 5.2.5 on 2025-08-11 14:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordrecovery_userlogin_userregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='password',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
