# Generated by Django 5.2.5 on 2025-08-12 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userlogin_email_remove_userlogin_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregistration',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'User Registration', 'verbose_name_plural': 'User Registrations'},
        ),
        migrations.RemoveField(
            model_name='passwordrecovery',
            name='email',
        ),
        migrations.RemoveField(
            model_name='passwordrecovery',
            name='recovery_token',
        ),
        migrations.AddField(
            model_name='passwordrecovery',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='passwordrecovery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
