# Generated by Django 5.2.5 on 2025-08-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userregistration_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='password',
        ),
    ]
