# Generated by Django 5.2.5 on 2025-08-12 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userregistration_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='user',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregistration',
            name='password',
            field=models.CharField(default='temporary-password', max_length=255),
            preserve_default=False,
        ),
    ]
