# Generated by Django 5.2.5 on 2025-08-12 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userregistration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordrecovery',
            name='token',
            field=models.CharField(default='placeholder-token', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordrecovery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userregistration'),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userregistration'),
        ),
    ]
