# Generated by Django 5.2.5 on 2025-08-14 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_wishlistitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='user_login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userlogin'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='product_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='product_image',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='LogoutEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userlogin')),
            ],
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='user',
        ),
    ]
