# Generated by Django 5.2.5 on 2025-08-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_wishlistitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
