# Generated by Django 5.2.5 on 2025-08-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_wishlistitem_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Client Profile', 'verbose_name_plural': 'Client Profiles'},
        ),
        migrations.AlterModelOptions(
            name='logoutevent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Logout Event', 'verbose_name_plural': 'Logout Events'},
        ),
        migrations.AlterModelOptions(
            name='passwordrecovery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Password Recovery', 'verbose_name_plural': 'Password Recoveries'},
        ),
        migrations.AlterModelOptions(
            name='userlogin',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Login', 'verbose_name_plural': 'User Logins'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-added_at'], 'verbose_name': 'Wishlist Item', 'verbose_name_plural': 'Wishlist Items'},
        ),
    ]
