# Generated by Django 4.2.3 on 2025-08-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graziella', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
